# Generated by Django 2.2.23 on 2022-03-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0005_remove_teacherdata_doj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherdata',
            name='status',
            field=models.TextField(choices=[('Active', 'Active'), ('Long Leave', 'Long Leave'), ('Sick Leave', 'Sick Leave'), ('Metarnity Leave', 'Metarnity Leave')], default='active'),
        ),
    ]
