# Generated by Django 2.2.23 on 2022-03-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0006_auto_20220314_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=150)),
                ('address', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='teacherdata',
            name='school',
            field=models.TextField(null=True),
        ),
    ]
