# Generated by Django 2.2.23 on 2022-03-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0007_auto_20220315_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.TextField()),
                ('document', models.FileField(upload_to='media')),
            ],
        ),
    ]
