# Generated by Django 4.0 on 2022-03-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0008_notifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalData',
        ),
        migrations.DeleteModel(
            name='TeacherData',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='id',
        ),
        migrations.AddField(
            model_name='notifications',
            name='posted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='file_id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
