# Generated by Django 4.0 on 2022-03-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0012_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='members',
            name='email',
            field=models.EmailField(default='chandanasamineni23@gmail.com', max_length=254, primary_key=True, serialize=False),
        ),
    ]
